apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/hnaung/flask-app-helm:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/hnaung/flask-app-helm:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: web
        chartPath: charts/web
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/hnaung/flask-app-helm'
image.tag: '{{.DIGEST_HEX}}'
